export default function useReact() {
  const React = [
    "What is React?",
    "What is useState() in React?",
    "What is useRef in React js?",
    "What are keys in React?",
    "What is JSX?",
    "What are the differences between functional and class components?",
    "What is the virtual DOM? How does react use the virtual DOM to render the UI?",
    "What are the differences between controlled and uncontrolled components?",
    "What are props in React?",
    "Explain React state and props?",
    "What is prop drilling in React?",
    "Explain About React Hooks?",
    "What is the use of useEffect React Hooks?",
    "What are Custom Hooks?",
    "What is Redux? Explain How we use in React.",
    "Explain data flow in Redux?",
    "Explain lifecycle method in React js?",
    "What is difference between export default and export in React js?"
  ];
  const JavaScript = [
    "Explain Hoisting in javascript?",
    "Difference between “ == “ and “ === “ operators?",
    "Difference between var, let and const keyword in javascript.",
    "Is javascript a statically typed or a dynamically typed language?",
    "What is NaN property in JavaScript?",
    "Explain passed by value and passed by reference?",
    "What do you mean by strict mode in javascript and characteristics of javascriptstrict-mode?",
    "Explain Higher Order Functions in javascript?",
    "Explain “this” keyword?",
    "Explain call(), apply() and, bind() methods?",
    "What is currying in JavaScript?",
    "What are some advantages of using External JavaScript?",
    "Explain Scope and Scope Chain in javascript.",
    "Explain Closures in JavaScript?",
    "What are object prototypes?",
    "What are callbacks?",
    "What is memoization?",
    "What is the use of a constructor function in javascript?",
    "What is DOM?",
    "What is the distinction between client-side and server-side JavaScript?",
    "What is the use of promises in javascript?",
    "What are the primitive and nonPrimitive data types in JavaScript?",
    "What is Ecmascript in Javascript?",
    "What is spread operator and Rest operator?",
    "What is deep copy and shallow copy in Javascript?",
    "What is difference between promise and callback in Javascript?",
    "What is event bubbling and event capturing in Javascript?",
    "What is higher order function in Javascript?",
    "How many way to create object in Javascript?",
    "What is throttling and debouncing in js?",
    "What is Null and undefined in javascript?",
    "What are the falsy values in javascript?",
    "What is setTimeOut and setInterval in Javascript?",
    "What is object.seal and object.freeze in Javascript?",
    "What is sessionStorage, localStorage , cookie?",
    "What are is map, filter, reducer in javascript?",
    "How to stop event propagation in Javascript?"
  ];
  const NodeJs = [
    "What is Node.js and how it works?",
    "How is Node.js better than other frameworks most popularly used?",
    "How do you manage packages in your node.js project?",
    "What are the advantages of using promises instead of callbacks?",
    "Why is Node.js single-threaded?",
    "What do you understand by callback hell?",
    "What is an event-loop in Node JS?",
    "What is node.js streams?",
    "What are node.js buffers?",
    "What is middleware?",
    "What is an Event Emitter in Node.js?",
    "What is a first class function in Javascript?"
  ];
  const MongoDB = [
    "Explain about MongoDB? When to use MongoDB.",
    "What is a Document in MongoDB?",
    "What is a Collection in MongoDB?",
    "What are Databases in MongoDB?",
    "What is the Mongo Shell?",
    "What are some features of MongoDB?",
    "How to add data in MongoDB?",
    "How do you Update a Document?",
    "How do you Delete a Document?",
    "How to perform queries in MongoDB?",
    "How is Querying done in MongoDB?",
    "What are the data types in MongoDB?",
    "What do you mean by Transactions?",
    "What is the Aggregation Framework in MongoDB?",
    "Explain the concept of pipeline in the MongoDB aggregation framework.",
    "What is a Replica Set in MongoDB?",
    "Explain the process of Sharding?",
    "Explain the term “Indexing” in MongoDB?",
    "What are Geospatial Indexes in MongoDB?"
  ];
  const MERN = [
    "What is an event-loop in Node JS?",
    "What is React?",
    "What is useState() in React?",
    "What is useRef in React js?",
    "What are keys in React?",
    "What is JSX?",
    "What are the differences between functional and class components?",
    "What is the virtual DOM? How does react use the virtual DOM to render the UI?",
    "What are the differences between controlled and uncontrolled components?",
    "What are props in React?",
    "Explain React state and props?",
    "What is prop drilling in React?",
    "Explain About React Hooks?",
    "What is the use of useEffect React Hooks?",
    "What are Custom Hooks?",
    "What is Redux? Explain How we use in React.",
    "Explain data flow in Redux?",
    "Explain lifecycle method in React js?",
    "What is difference between export default and export in React js?",
    "What is Node.js and how it works?",
    "How is Node.js better than other frameworks most popularly used?",
    "How do you manage packages in your node.js project?",
    "What are the advantages of using promises instead of callbacks?",
    "Why is Node.js single-threaded?",
    "What do you understand by callback hell?",
    "What is node.js streams?",
    "What are node.js buffers?",
    "What is middleware?",
    "What is an Event Emitter in Node.js?",
    "What is a first class function in Javascript?",
    "Explain about MongoDB? When to use MongoDB.",
    "What is a Document in MongoDB?",
    "What is a Collection in MongoDB?",
    "What are Databases in MongoDB?",
    "What is the Mongo Shell?",
    "What are some features of MongoDB?",
    "How to add data in MongoDB?",
    "How do you Update a Document?",
    "How do you Delete a Document?"
  ];
  const HR = [
    "Tell me somthing about your self?",
    "Why did you change you path?",
    "What is your Strength?",
    "What is your Weakness?",
    "What does your perfect workday look like? Take me through it from the start till the end.",
    "What are your career Objectives? / Where do you see yourself in 5 years?",
    "Why Should we hire you?",
    "Why do you want to work with us?",
    "When did you realize your interest in coding?",
    "What would be your expected salary?",
    "Why did you join Masai school?",
    "Which project you did at Masai school did you find most challenging and why?",
    "How do you see your vision aline with the vision of the company?"
  ];

  return { React, JavaScript, NodeJs, MongoDB, MERN, HR };
}
